### PR TITLE
Update master with most recent changes

### PR DESCRIPTION
**Pull request by cooperhatfield**
I guess I should've been making my changes on 'work' this whole time... I'll do that going forward. I think there's been enough changes that there should be a new release. 

In this PR I've added the Caputo methods, a change to support numpy data types in checkValues, and the speed improvement for the gamma function. I've updated the changelog with all changes since 2019, and bumped the version number in setup.py to 0.4.

If you agree with my changes, merge this and update the package :)

Here's a list of all changes since the last release on pypi, as seen in the changelog:

### Added

  - 'CRONE' - calcualte GL differintegral operator using CRONE
  - Include future print function support
  - 'isPositiveInteger' - check if a number is and integer and positive
  - 'PCsolver' - solve initial value fractional ODEs using the predictor-corrector method
  - Caputo differintegral using the L1, L2, and L2C methods
  
### Modified
  
 - Changed the way `isInteger` checks the given value
 - resolved bug in 'CRONE' method
 - updated Pochhammer symbol implementation to support a larger domain of inputs
 - 'checkValues' now supports numpy data types
 - 'Gamma' now uses `math.gamma` for real values to speed up computation

### CODE REVIEW

**Comment by cooperhatfield** [comment]
Hey Matt, just wondering if you've had a chance to take a look at this. Obviously it shouldn't be a priority, but I just think it would be nice to get a release out addressing some of the issues that have been resolved, to ensure the package is kept up with the needs of those who may use it!

**Review by uniformlyMatt — APPROVED** [review]
Looks great! Thank you for including test cases as well. With the addition of fractional differential equations should we release v1.0?

**Comment by uniformlyMatt** [comment]
Reviewed and approved! Thank you for all your work on this - I've added you
as an admin on the repo since I haven't been paying much attention to the
project. Should we release v1.0 since you've included fractional
differential equations?

**Comment by cooperhatfield** [comment]
Thanks! I've noticed I'm an admin now, I just don't have the ability to update the package on pypi... 

I don't know if you have a "vision" for what this package should end up supporting, but if you think that this would be good for a first big release, I would agree!

**Comment by uniformlyMatt** [comment]
I haven't given much thought to an overall vision. I've got a new job at a
financial institution and haven't had as much time to work on the package.
You've done quite a lot of work for this most recent release, so I'd like
to make you the project maintainer/co-owner. Do you have a PyPi user name
so I can add you?

**Comment by cooperhatfield** [comment]
I just made an account, the username is "cooperhatfield", same as here.

**Comment by cooperhatfield** [comment]
Hi @uniformlyMatt, I saw the action you made for updating the package on PyPi, and merged it in, thank you! But I still don't have access to the package on PyPI. I know you're busy, but could you either add me to the package on PyPI, or add the API key to the secrets section on the repo? That way the action will be fully functional.

**Comment by uniformlyMatt** [comment]
Hi Cooper! I've invited you as an Owner of differint on PyPi!

**Pull request merged**
